### ISSUE TITLE
Tweet count

### ISSUE THREAD

**Issue by lukas2511** [andir/ipv6.watch#14]
Not sure if this is really possible, but a counter how many tweets with keyword `ipv6` and a specific twitter-handle were ever sent would be nice, just to have an indication on how much pressure is put on those sites.

So for example with DeutscheWelle you'd count tweets with keywords `@deutschewelle` and `ipv6`. Which at the moment probably is exactly 1.

**Comment by schollz** [comment]
Working on it!

**Comment by flokli** [comment]
Seems like this is more complex, see #21 for details. Closing for now.
