### ISSUE TITLE
Add popular sites

### ISSUE THREAD

**Issue by l0b0** [andir/ipv6.watch#85]
Some sites which come to mind:

- pinboard.in, the successor to Delicious
- hub.docker.com, arguably more important than docker.com for IPv6 reachability
- bbc.co.uk; they were really slow with TLS adoption
- nixos.org, an up-and-coming Linux distro
- store.steampowered.com, probably the most popular gaming web site out there
- All of the most popular websites, by some metric (for example, [Wikipedia](https://en.wikipedia.org/wiki/List_of_most_popular_websites))

I've not tested compliance, but these are important in their respective fields, and probably would serve as goalposts if they are already compliant.

**Comment by mweinelt** [comment]
Thanks for your interest. We're already looking at a few of the sites you've mentioned. For all others we would be glad to receive pull requests with icons that have a reasonable license and a twitter reference.

----

> hub.docker.com, arguably more important than docker.com for IPv6 reachability

https://github.com/andir/ipv6.watch/blob/bd581ac70b900ba0c1c38d9dbc06d0ae80832f91/conf.yaml#L159-L167

> nixos.org, an up-and-coming Linux distro

https://github.com/andir/ipv6.watch/blob/bd581ac70b900ba0c1c38d9dbc06d0ae80832f91/conf.yaml#L367-L375

> store.steampowered.com, probably the most popular gaming web site out there

https://github.com/andir/ipv6.watch/blob/bd581ac70b900ba0c1c38d9dbc06d0ae80832f91/conf.yaml#L459-L466

**Comment by l0b0** [comment]
Ah whoops, how did I miss those!? Sorry for the noise; I'll see if I can add the other sites reasonably soon.

**Comment by l0b0** [comment]
[Done](https://github.com/andir/ipv6.watch/pull/89) and [done](https://github.com/andir/ipv6.watch/pull/87).
